### ISSUE TITLE
按你的教程不成功，有几个问题请教

### ISSUE THREAD

**Issue by RockZhou8** [onlyice/asus-merlin-cross-the-gfw#2]
1.我的post-mount是在jffs/scripts/下面，不是直接在jffs下

2.S22shaodowsock文件要不要如下编辑？因为你的不成功，我找了网上其他的
       将"PROCS=ss-local"修改为"PROCS=ss-redir"(我们要运行ss-redir转发)，
       将 ARGS="-c /opt/etc/shadowsocks.json" 修改为 ARGS="-b 0.0.0.0 -c /opt/etc/shadowsocks.json"

**Comment by onlyice** [comment]
跟 S22shadowsocks 文件没关系，这是一种 init script，我的教程没有采用这种机制。

其他的调试不能帮到你了，祝你好运

Rock Zhou <notifications@github.com>于2016年3月13日周日 下午4:20写道：

**Comment by RockZhou8** [comment]
我是的RT-N16
所以1.post-mount在jffs/下也会运行吗？
2.我不那么改的话，在putty里ps，进程里没有ss-redir，手动运行`ss-redir -c /tmp/opt/etc/shadowsocks.json &`，提示我已经被绑定了

**Comment by onlyice** [comment]
1. 需要看你刷的固件文档
2. 可以用 netstat 看看端口被哪个进程绑定
