### ISSUE TITLE
购买新的路由器我该选 MIPS 还是 ARM ?

### ISSUE THREAD

**Issue by zw963** [onlyice/asus-merlin-cross-the-gfw#3]
嘿， 最近想买一个路由器，用途就是 ss.

我想问下， 是否针对不同的架构，使用 ss 会存在一些不兼容的问题？

我应该买一些比较便宜的 MIPS (N66U, AC-66U, MIPS), 还是最好买贵一点的？ (AC-68U, ARM)?

谢了。

**Comment by onlyice** [comment]
Hi 你好，我不太了解这些 CPU 上的差异，理论上是能刷 OpenWRT / Merlin 的都可以用 SS。

但是 SS 需要对网络流量加解密，所以挺耗 CPU 的，可以留意下别人的使用体验。

**Comment by zw963** [comment]
Thanks.
