### ISSUE TITLE
AC66U, merlin 最新稳定版， ss 2.4.5 总是段时间异常退出。

### ISSUE THREAD

**Issue by zw963** [onlyice/asus-merlin-cross-the-gfw#4]
梅林用的官方的最新稳定版： 380.59， 非修改版。
ss 使用 entware 安装, jffs 分区是一个很老的 U 盘。

@onlyice , 你有遇到短时间内（五到十分钟） process 就退出的情况吗？

如果你的很稳定，方便说下我们存在的差异吗？ 

谢谢。

(顺便说一声： 我还启动了一个 privoxy 进程， 那个轻易是不会退出的)

**Comment by onlyice** [comment]
好像没有遇到过，不过我已经不再用这种方式了（因为我的 ）

**Comment by onlyice** [comment]
操作失误。。因为我这边到 VPS 延时丢包都太严重，而路由器上面又难以部署双边加速的服务，因此没有在路由器上跑 SS 了。

调试的话可以看看 `/var/log/messages` ，可能有出错的相关信息。有无可能是内存不够直接被 kill 了？我当时用 Privoxy 时非常不稳定，不记得为啥了

**Comment by zw963** [comment]
@onlyice 下面没东西，就一个 /var/log/commit_ret 日志没得看。

我刚注意到 ss-local 有个 -v  参数，代表 verbose 模式， 我等下试着重定向一个新的到日志文件看。

谢了， 有结果我会在这里报告。

**Comment by zw963** [comment]
嘿，我没有继续探究到底为啥退出了。我只是加了个 crontab, 每一分钟检测一下。

谢谢。
