### ISSUE TITLE
有关教程中 dnsmasq 部分的疑惑。

### ISSUE THREAD

**Issue by zw963** [onlyice/asus-merlin-cross-the-gfw#5]
按照教程我配置了， 还未启动测试。

但是有些挥之不去的疑惑， 觉得那里不太对劲儿, 特请教。

因为教程中提供的 foreign_domains.conf, accelerated-domains.china.conf  感觉时间有点老了，所以，我直接用的 [dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list) 提供的配置文件.

但是我感觉好奇怪， 你的配置文件倒是没有多大疑问， 无非就是特定的域名使用特定的 DNS 解析之类的， 但是我在 dnsmasq-china-list  项目中发现 bogus-nxdomain.china.conf 文件， 内容完全和之前的不一样。

```sh

#DNSPai
bogus-nxdomain=123.125.81.12
bogus-nxdomain=101.226.10.8

#Nanfang Unicom (nfdnserror1.wo.com.cn to nfdnserror17.wo.com.cn)
bogus-nxdomain=220.250.64.18
bogus-nxdomain=220.250.64.19
bogus-nxdomain=220.250.64.20
bogus-nxdomain=220.250.64.21
bogus-nxdomain=220.250.64.22
bogus-nxdomain=220.250.64.23
bogus-nxdomain=220.250.64.24
bogus-nxdomain=220.250.64.25
```

我想请教的问题是：

1. 这些文件名难道是固定的？  foreign_domains 是随便起的吗? 
2. 内容中的 server, bogus-nxdomain 都是 dnsmasq 可识别的的关键字？ 
    
谢谢。

**Comment by onlyice** [comment]
1. 名字是可以随便起的，印象中是 `. conf` 结尾就可以了，而且你需要在配置里指定 conf-dir。具体可以看看 dnsmasq 的 man page
2. 是可以‘识别的关键字，man page 里应该有提及。这种远古项目的文档似乎比较零散，可能需要仔细啃啃 man page 。bogus-nxdomain 的作用在我的文章里有提及，可以搜一下

**Comment by zw963** [comment]
完美解答， 谢谢！

**Comment by zw963** [comment]
嘿，今天又有时间，把 dnsmasq 尝试配置了一下，没有成功。

问题是： 当我添加下面的脚本进来.

```sh
echo conf-dir=/opt/etc/dnsmasq-conf > /jffs/configs/dnsmasq.conf.add
```

无论 /opt/etc/dns-masq-conf 这个目录是不是存在， 只要一重启，
WIFI 就连不上了(能看到)，原因是 DHCP  不工作了, 只有自己赋予
静态 IP 才工作。

请问遇到类似情况吗？

**Comment by zw963** [comment]
我的配置如下：

1. echo conf-dir=/opt/etc/dnsmasq-conf > /jffs/configs/dnsmasq.conf.add

2. /opt/etc/dnsmasq-conf 目录下文件
admin@RT-AC66U-20F0:/tmp/mnt/sda/entware/etc# tree -sh dnsmasq-conf/
dnsmasq-conf/
|-- [735K]  accelerated-domains.china.conf
|-- [2.2K]  bogus-nxdomain.china.conf
|-- [  25]  foreign_domains.conf
`-- [ 39K]  google.china.conf

之前怀疑 accelerated-domains.chiina.conf 700 多 k 太大所致， 后来发现，我拔掉 u 盘，
/opt 不存在了, 问题依旧。

**Comment by onlyice** [comment]
之前用老版本梅林固件没遇到过，后来升级到新版本也出现了，于是我就直接恢复出厂设置没在继续折腾了。。

Billy.Zheng <notifications@github.com>于2016年7月8日周五 上午1:38写道：

**Comment by zw963** [comment]
我给官方项目， 新建了一个 issue.

**Comment by onlyice** [comment]
好较真，赞👍

**Comment by zw963** [comment]
对方回复了，配置问题。

https://github.com/RMerl/asuswrt-merlin/issues/968#issuecomment-231549758

**Comment by zw963** [comment]
嘿，那个配置问题解决了， 有个配置出错，造成 dnsmasq 没有启动，dnsmasq 还兼具 dhcp 功能，自然无法连接了。

我还有一个疑惑不解的问题请有空解释下.

1. accelerated-domains.china.conf 文件中的末尾 114.114.114.114 全部替换为 #, 是啥意思？
    这里的 # 是注释？ 还是特殊含义？ 那里有 # 的文档，谢谢。

2. server=/#/127.0.0.1:5353, 这个 # 又是啥意思？ 我感觉 # 有点 `默认值` 或 `包含所有` 的含义。
    不知道理解对不对，您可以提供个这方面文档的连接吗?

**Comment by zw963** [comment]
我发现下面的代码， 访问 ip138 仍然使用我的 VPS 代理 (127.0.0.1#5353)。

```sh
server=/.ip138.com/114.114.114.114
server=/#/127.0.0.1#5353
```

似乎上面那一句没有生效, 我只想所有 accelerated-domains.china.conf 中指定的中国域名
之外的 dns 才走代理，不知道该怎么配置。请指教。

**Comment by onlyice** [comment]
> 1. accelerated-domains.china.conf 文件中的末尾 114.114.114.114 全部替换为 #, 是啥意思？
这里的 # 是注释？ 还是特殊含义？ 那里有 # 的文档，谢谢。

`#` 就是表示走默认的 DNS 服务器。因为我觉得 `114.114.114.114` 这种 DNS 服务器解析出来的效果，不会比运营商指派给你的 DNS 服务器好。当然运营商可能会插一些广告，但是我的深圳电信不这么流氓。

> 2. server=/#/127.0.0.1:5353, 这个 # 又是啥意思？ 我感觉 # 有点 默认值 或 包含所有 的含义。
不知道理解对不对，您可以提供个这方面文档的连接吗?

你的理解是对的，就是其他域名默认走 127.0.0.1:5353 这个域名进行解析。

**Comment by onlyice** [comment]
@zw963 

> `server=/.ip138.com/114.114.114.114`

这样写应该是错的（我没验证过），参考 dnsmasq 的 [man page](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) 中的`-S, --local, --server` 选项。

**Comment by zw963** [comment]
@onlyice , 已解决， 非常感谢。

经过多次尝试，我透明代理采用了一个改进版的方案.

### 安装新版的 iptables 和 ipset4.

```sh
$ opkg install iptables ipset4
```

### DNSMASQ 配置 
首先确定  dnsmasq 支持 ipset. 
```sh
$ dnsmasq -v |grep ipset
```
最新稳定板 merlin 内置的 dnsmasq 已经支持 ipset, 所以直接可用。

然后就可以采用 ipset+dnsmasq 自动的动态更新 accelerated-domains.china.conf  文件中的国内白名单域名对应的 IP 到 iptables , 使用这种方式， 就不需要刚开始那一大段代表国内的 ip 地址了. 仅需要维护一个国内白名单列表(dnsmsq-china-list)即可。而且 bestroutetb 工作似乎也不好，到 100% 就停在那里了.

下面是一段代码，生成了两个 dnsmasq 配置文件, 分别对应的 `国内白名单DNS` 和 `国内白名单的ipset`, 当你访问白名单中的某个网址时， dnsmasq 会根据 DNS 取得域名的 IP, 并且将 IP 其加入指定的 ipset (我起的 ipset 名字叫做 FREEWEB), 稍后在 iptables 中，只要符合这个 FREEWEB 的流量， 直接 RETURN 好了。

```sh
wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf -O ./dnsmasq-conf/accelerated-domains.china.conf
sed -r 's#server=(.*)114.114.114.114#ipset=\1FREEWEB#' ./dnsmasq-conf/accelerated-domains.china.conf > dnsmasq-conf/accelerated-domains-ipset.china.conf
sed -i "s|^\(server.*\)/[^/]*$|\1/#|" ./dnsmasq-conf/accelerated-domains.china.conf
```
此外，还需要保留原来的那个 foreign_domains.conf. 

### IPTABLES 配置

下面的是新的  iptables 规则，和原先类似， 但是加了一条，凡是 dnsmasq 动态加入 ipset 
FREEWEB 中的 ip, 直接 RETURN. 最后剩下的，才转发到 1081 (ss-redir 监听端口)
如你所见，可比原来的 iptables 小多了， 而且不需要再更新了。: )

```cl
if /opt/sbin/ipset -N FREEWEB iphash; then
    if /opt/sbin/iptables -t nat -N SHADOWSOCKS; then
        /opt/sbin/iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
        /opt/sbin/iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
        /opt/sbin/iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
        /opt/sbin/iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
        /opt/sbin/iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
        /opt/sbin/iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
        /opt/sbin/iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
        /opt/sbin/iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN

        # 如果有很多服务器，并且所有目标服务器都是同样的端口, 用法如下
        # /opt/sbin/iptables -t nat -A SHADOWSOCKS --dport 22334 -j RETURN
        /opt/sbin/iptables -t nat -A SHADOWSOCKS -d 202.56.13.13 -j RETURN

        /opt/sbin/iptables -t nat -A SHADOWSOCKS -m set --match-set FREEWEB dst -j RETURN

        /opt/sbin/iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1081

        /opt/sbin/iptables -t nat -I PREROUTING -p tcp -m multiport --dports 80,443 -j SHADOWSOCKS
        /opt/sbin/iptables -t nat -I OUTPUT -p tcp -m multiport --dports 80,443 -j SHADOWSOCKS
        # /opt/sbin/iptables -t nat -A SHADOWSOCKS -p tcp --syn -m connlimit --connlimit-above 32 -j RETURN
    fi
fi
```

你可以试下这个方案， 如果不错， 可以更新下你的文档。
非常感谢你的帮助！

**Comment by zw963** [comment]
你可以通过 /opt/sbin/ipset -L FREEWEB 查看 ipset 中， dnsmasq 动态加入的 IP 列表. 可以看到随着访问国内网站的增多， 这个列表也是动态更新的。

**Comment by onlyice** [comment]
太赞了，我抽时间尝试下，你使用起来体验如何呢？

对于我来说，目前影响翻墙流畅性的瓶颈在 VPS 线路（我不愿意花大价钱去买好的服务），而路由上不好搭建 TCP 加速的服务，这个还没有找到太好的办法。如果你也遇到了这个问题，求分享解决经验哈 :smiley:

**Comment by zw963** [comment]
我用的香港的 VPS. 一个月 $9,  200G 流量，不限速，感觉可能贵点，不过好在网通电信速度都非常好， 如果是电信才牛， 基本上就是国内直连。

你有兴趣，我可以给你发邮件. 

其实 vultr 也不错啊, 日本的服务器。就是网速差了点，有限速。

**Comment by zw963** [comment]
> 太赞了，我抽时间尝试下，你使用起来体验如何呢？

体验上没看出啥差别， 不过启动路由时，很明显不需要执行那一大堆 iptables, 这是一个很大的红利。
感觉应该好点吧。

**Comment by zw963** [comment]
@onlyice , 我感觉用手机上网，比之前的那种几千条 iptables 的方案速度明显要快啊。

我新建了一个项目，打包了个一键安装脚本了, 你有空试下了， 给点反馈。
其中也包含对这个 issue 的引用。

https://github.com/zw963/asuswrt-merlin-transparent-proxy
