### ISSUE TITLE
ss-redir似乎总是不成功

### ISSUE THREAD

**Issue by tavimori** [onlyice/asus-merlin-cross-the-gfw#6]
按照Onlyice的方案，我可以成功进行dns转发了，ss-tunnel方面一直没有问题，但是ss-redir一直不行。日志显示ss-redir已经监听了1080，net-stat也表示1080被占用，但是我没有应用路由表之前，通过telnet测试路由器1080的socks代理都是始终不成功，提示Connection Reset。应用路由表以后，国内可以，国外就不行了。想问一下是什么原因呢？谢谢了！（两个版本的ss都试过了，机子是88u最新的merlin。

**Comment by onlyice** [comment]
Hi，我觉得可以在你的电脑上抓包看看，同时可以看看 `ss-redir` 有没有 log 输出（我不确定他会不会打 log）。

**Comment by tavimori** [comment]
谢谢回复，我在电脑上抓包，似乎第一次tcp握手就被拒了，我在路由器上调试iptables很久都找不出原因，似乎只有ss的这个端口工作不了。Anyway，我直接装了koolshare的固件了。不折腾了。
不过仔细想想ss-redir是不是socks代理我也不是很确定。

**Comment by onlyice** [comment]
赞，人生苦短，支持不折腾
