### ISSUE TITLE
 merlin 如何安装 node.js

### ISSUE THREAD

**Issue by willin** [onlyice/asus-merlin-cross-the-gfw#7]
以及运行效率如何？ 
512内存应该够用了吧

**Comment by onlyice** [comment]
相信你的聪明智慧可以找到这个问题的答案！

**Comment by onlyice** [comment]
认真的答复一下。目前似乎没有预编译好的 Node.js 二进制包可以在 Asus Merlin 用，而且很_可能_（我没考证过）Node.js 也不支持 ARM 平台。你可以这样：

1. 先看看 Node.js 是否支持 ARM 平台
2. 如果支持，找找有没有预编译好的 Node.js 二进制包
3. 如果没有，看看能否自己做交叉编译
4. 如果编译不出来，就放弃吧

**Comment by onlyice** [comment]
认真地答复下。Node.js [支持 ARM 平台](https://nodejs.org/en/download/)，所以你可以：

1. 找下 opkg 上有无预编译好的 Node.js 二进制包可以直接安装
2. 如果没有，看看 Node.js 官方提供的 ARM 包能否直接用（我看到是预编译好的了）
3. 如果不能用，看看能不能自己交叉编译一个

**Comment by willin** [comment]
asus 的路由器不是 mips平台吗？

**Comment by onlyice** [comment]
啊我用的 NetGear R7000 是 ARM 的，没留意到你是华硕路由器。

嵌入式我也一窍不通 :rofl:
