### ISSUE TITLE
shadowsocks.json 文件问题

### ISSUE THREAD

**Issue by xzdbd** [onlyice/asus-merlin-cross-the-gfw#8]
Hi onlyice,

请教一下，你的shadowsocks.json文件是怎么样的？

`{
	"server": "SS-SERVER-IP",
	"server_port": 8389,
	"local_address": "192.168.1.1",
	"local_port": 1080,
	"password": "password",
	"timeout": 60,
	"method": "aes-128-cfb"
}`

我用上面的配置，ss-tunnel DNS转发遇到了问题。local_address参数具体需要填什么呢？
是 192.168.1.1 (路由器的IP), 172.0.0.1 还是 0.0.0.0 ？

望赐教。

**Comment by onlyice** [comment]
建议 `0.0.0.0`；但是目测跟 ss-tunnel DNS 转发没有太大关系。

用 `0.0.0.0` 可以避免一些简单的问题（因为这样会绑定所有端口）。

**Comment by xzdbd** [comment]
我按照你的方法设置dnsmasq

`
ls /jffs/dnsmasq-conf/
accelerated-domains.china.conf  foreign-domains.conf

ls /jffs/configs/
dnsmasq.conf.add

cat /jffs/configs/dnsmasq.
conf.add
conf-dir=/jffs/dnsmasq-conf
`

ss-redir启动了， dnsmasq重启了。

然后我手动启动ss-tunnel，访问google facebook等网站，有找不到DNS的错误。

好像DNS请求并没有转发到ss-tunnel监听的端口，日志如下。

`
 ss-tunnel -c /opt/etc/shadowsocks.json -b 127
.0.0.1 -l 7913 -L 8.8.8.8:53 -u -v
 2017-04-27 10:10:43 INFO: initializing ciphers... aes-128-cfb
 2017-04-27 10:10:43 INFO: UDP relay enabled
 2017-04-27 10:10:43 INFO: listening at 127.0.0.1:7913
 2017-04-27 10:10:43 INFO: running from root user
`

可能是什么原因引起的呢？ss 服务端开启了UDP Relay以及tcp udp的端口了。

谢谢。

**Comment by onlyice** [comment]
用 `netstat` 检查下 7913 端口是不是在侦听呢？

**Comment by xzdbd** [comment]
```
netstat -a | grep 7913
tcp        0      0 localhost.localdomain:7913 0.0.0.0:*               LISTEN
udp        0      0 localhost.localdomain:7913 0.0.0.0:*


ps | grep ss
 5205 admin     5748 S    ss-redir -c /opt/etc/shadowsocks.json
 5218 admin     5220 S    ss-tunnel -c /opt/etc/shadowsocks.json -b 127.0.0.1

```

Any idea?

Thanks.

**Comment by onlyice** [comment]
看起来一切正常，终极办法是抓包看看 DNS 请求包跟回包。考虑在你的电脑上 WireShark 或者 tcpdump 一下试试。
